### ISSUE TITLE
pip install bittrex-websocket? 

### ISSUE THREAD

**Issue by rightx2** [slazarov/python-bittrex-websocket-aio#1]
Isn't it same command with `https://github.com/slazarov/python-bittrex-websocket` ?

Do they use the same command to install?

Another question:
- What is the BIGGEST difference with the previous version(https://github.com/slazarov/python-bittrex-websocket)? Does the previous one also run as asynchronously? (Sorry for asking but I'm kinda socket & asynchronous coding virgin...)

**Comment by slazarov** [comment]
Hi, I haven’t published the package in Pypi so you can currently install it from github only. 
The Pypi part in the readme is a left over from copy pasting the readme from the other library. I will update it.

You can check the top part of the readme to see what the current differences are and what the future plans are. The main difference is that the legacy socket uses gevent while this one uses asyncio. You can check online what the differences between the two are.

**Comment by slazarov** [comment]
He installation instructions have been fixed and since this is not package related issue, I am closing it.

**Comment by rightx2** [comment]
@slazarov Which one is perform faster or efficient? Just library(gevent vs asyncio) preferece?

**Comment by slazarov** [comment]
I would use asyncio. Note that the legacy version doesn’t use gevent anymore, I haven’t updated the docs yet.
