### ISSUE TITLE
Request to "merge" with CryptoFeed

### ISSUE THREAD

**Issue by svabra** [slazarov/python-bittrex-websocket-aio#19]
I would recommend to "merge" this effort with the CryptoFeed library.
https://github.com/bmoscon/cryptofeed

**Comment by fmichaud** [comment]
+1

**Comment by svabra** [comment]
@fmichaud I've already done it. @bmoscon will have a look at the PR.
https://github.com/bmoscon/cryptofeed/pull/892

**Comment by fmichaud** [comment]
> @fmichaud I've already done it. @bmoscon will have a look at the PR.
> https://github.com/bmoscon/cryptofeed/pull/892
> 

Waoh. Thanks. 🙂

**Comment by svabra** [comment]
To everyone. The websocket functionality of this library I've included (for most parts) in the cryptofeed library. The rest is covered by ccxt.
