### ISSUE TITLE
uvloop - Windows no longer supported

### ISSUE THREAD

**Issue by adotorc** [slazarov/python-bittrex-websocket-aio#2]
It seems that this new version using asyncio depends on uvloop that is not supported in Windows systems.
 

> C:\>pip install bittrex-websocket-aio
> Collecting bittrex-websocket-aio
>   Using cached bittrex_websocket_aio-0.0.0.2.2-py2.py3-none-any.whl
> Collecting uvloop>=0.9.1 (from bittrex-websocket-aio)
>   Using cached uvloop-0.9.1.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\~\AppData\Local\Temp\pip-build-1qo1p6yg\uvloop\setup.py", line 10, in <module>
>         raise RuntimeError('uvloop does not support Windows at the moment')
>     RuntimeError: uvloop does not support Windows at the moment

**Comment by meister245** [comment]
If you are running Windows 10, you can use the linux subsystem, make a virtualenv for python 3 and run your project through /mnt/c/<path>

**Comment by adotorc** [comment]
That means cheating a linux subsystem into the equation and generating a linux binary, not a windows one with PyInstaller.

Currently I generate several binaries for several so-architecture combos, and the ones with windows are no longer available in this version of the library due to the new requisites not being windows compatible. 

So in order to maintain full compatibility, the old legacy edition remains as the only option.

**Comment by slazarov** [comment]
Hello @adotorc, your point is completely valid. Before anything else the package should provide its functionality and then achieve optimizations. I will make uvloop optional and update the documentation.

**Comment by slazarov** [comment]
Update `https://github.com/slazarov/python-signalr-client` through github or pypi.

**Comment by slazarov** [comment]
Issue is fixed, closing.
