### ISSUE TITLE
Queston: Authorization Logic when submit orders

### ISSUE THREAD

**Issue by ryarom148** [slazarov/python-bittrex-websocket-aio#3]
Good afternoon!
I am making a trading application and since the buy/sell orders are submitted through REST API, I wonder how to implement the authorization logic:
1) authorize through REST API and authorize independently through Websocket ?
2) do you have any example of to API working together?

Thanks

**Comment by slazarov** [comment]
What API functions do you refer to when you say 'authorise'?

The only account-based info you can get through the socket is Balance Delta and Order Delta. Any buy/sell orders are sent through the API. For simplicity, if you want to be able to receive live data and perform trades, just open a separate thread for the trades.

**Comment by ryarom148** [comment]
thanks

**Comment by slazarov** [comment]
Closing.
