### ISSUE TITLE
using the beta websocket connection, should be using `https://socket.bittrex.com/signalr`

### ISSUE THREAD

**Issue by jaredtkatz** [slazarov/python-bittrex-websocket-aio#4]
https://github.com/slazarov/python-bittrex-websocket-aio/blob/fdb6e01fd1cbe03b6ba9595a1ccbc83e3d554621/bittrex_websocket/_constants.py#L23

See here:
https://bittrex.github.io/#connecting

**Comment by slazarov** [comment]
I recommend using the beta endpoint until Bittrex gives further notice that it is removing it. The reason being is that it randomly enables Cloudflare on the official endpoint.

Of course, you can choose to change the url by passing a new url upon instantiating. Check:
https://github.com/slazarov/python-bittrex-websocket-aio#custom-url

**Comment by jaredtkatz** [comment]
Ah, was not aware of the Cloudflare issue. Good call. Thanks for the quick response!
