### ISSUE TITLE
websocket_client doesn't use custom url

### ISSUE THREAD

**Issue by dyschwartz** [slazarov/python-bittrex-websocket-aio#7]
Line 59 of websocket_client.py is:
```
connection = Connection(BittrexParameters.URL, Session())
```

Shouldn't it be:
```
connection = Connection(self.url, Session())
```
?

**Comment by slazarov** [comment]
Good catch, fixed https://github.com/slazarov/python-bittrex-websocket-aio/commit/e651cfc2093ddfe9b527196bcd887404d679c2d4
